name: clingraph
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - clingo
  - clorm>=1.3.6
  - dot2tex
  - imageio==2.21
  - networkx
  - python-graphviz
  - jsonschema
  - libxml2
  - jinja2
